version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s: %(levelname)s >> [%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: './logs/tichu-app.log'
    maxBytes: 10485760
    backupCount: 10
    encoding: utf-8

  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: './logs/tichu-app-error.log'
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8

root:
  level: INFO
  handlers: [console, file_info, file_error]
  propagate: no